import os
from datetime import datetime
from fpdf import FPDF

class TokenProcessor:
    def __init__(self):
        try: 
            from database_manager import RayaDB
            self.db = RayaDB()
        except: self.db = None
        self.logo_path = "image_1.jpeg" 
        self.patient_img_path = "patient_photo.jpg" 

    def get_triage_info(self, report):
        rep = str(report).lower()
        dept, color, level = "GENERAL MEDICINE", (0, 128, 0), "NORMAL (GREEN)"
        if any(x in rep for x in ["heart", "chest", "cardiac", "breath"]): dept, color, level = "CARDIOLOGY", (255, 0, 0), "EMERGENCY (RED)"
        elif any(x in rep for x in ["tooth", "dental", "gum"]): dept, color, level = "DENTAL DEPT", (0, 128, 0), "NORMAL (GREEN)"
        elif any(x in rep for x in ["bone", "fracture", "joint", "neck", "back"]): dept, color, level = "ORTHOPEDICS", (255, 165, 0), "URGENT (YELLOW)"
        return dept, color, level

    def generate_pdf(self, data, report, dept_name, triage_color, triage_level):
        try:
            pdf = FPDF()
            pdf.add_page()
            
            if os.path.exists(self.logo_path):
                with pdf.local_context(fill_opacity=0.08):
                    pdf.image(self.logo_path, x=60, y=95, w=90) 

            pdf.set_font("Arial", 'B', 24)
            pdf.set_text_color(0, 51, 102) 
            pdf.cell(0, 12, "OXWAY SMART HEALTHCARE", align='L')
            pdf.ln(15)

            if not os.path.exists(self.patient_img_path):
                pdf.set_draw_color(200, 200, 200)
                pdf.rect(160, 35, 35, 40)
                pdf.set_font("Arial", '', 7); pdf.set_text_color(150, 150, 150)
                pdf.text(163, 55, "NO PHOTO")

            pdf.set_font("Arial", 'B', 14); pdf.set_text_color(0)
            pdf.cell(70, 15, f"MAJOR ID: {data['major_id']}", border=1, align='C')
            pdf.cell(70, 15, f"SUB TOKEN: {data['sub_token']}", border=1, align='C')
            pdf.ln(20)
            
            pdf.set_fill_color(*triage_color)
            pdf.set_text_color(255)
            pdf.set_font("Arial", 'B', 12)
            pdf.cell(140, 10, f" DEPT: {dept_name} | PRIORITY: {triage_level}", fill=True, align='C')
            pdf.ln(15)

            pdf.set_text_color(0); pdf.set_font("Arial", 'B', 11)
            pdf.cell(0, 10, f"PATIENT: {str(data['name']).upper()}")
            pdf.ln(7)
            pdf.set_font("Arial", '', 10)
            pdf.cell(0, 7, f"AGE: {data['age']} | MOBILE: {data['mobile']} | DATE: {data['date']}")
            pdf.ln(10)
            pdf.line(10, pdf.get_y(), 150, pdf.get_y()) 
            pdf.ln(5)

            pdf.set_font("Arial", 'B', 11)
            pdf.cell(0, 7, "CHIEF COMPLAINT:", 0, 1)
            pdf.set_font("Arial", '', 10)
            # Filter name/problem for non-ASCII just in case
            clean_prob = "".join(i for i in str(data.get('main_problem', '')) if ord(i) < 128)
            pdf.multi_cell(140, 7, clean_prob.upper())
            pdf.ln(5)

            pdf.set_font("Arial", 'B', 11)
            pdf.cell(0, 10, "CLINICAL SUMMARY & FINDINGS:")
            pdf.ln(8)
            
            pdf.set_font("Arial", '', 10)
            points = report.split('\n')

            for point in points:
                # CRITICAL: This line strips out Hindi characters to prevent PDF crashes
                clean_text = "".join(i for i in point if ord(i) < 128).replace('*', '').replace('#', '').strip()
                if len(clean_text) > 3:
                    pdf.set_x(15) 
                    pdf.multi_cell(170, 7, f"- {clean_text}", align='L')
                    pdf.ln(1)

            pdf.set_y(-25)
            pdf.set_font("Arial", 'I', 8); pdf.set_text_color(120, 120, 120)
            pdf.cell(0, 10, "Generated by RAYA AI - Oxway Smart Healthcare Systems", align='C')

            os.makedirs("tokens", exist_ok=True)
            path = f"tokens/{data['sub_token']}.pdf"
            pdf.output(path)
            return path
        except Exception as e:
            print(f"PDF Error: {e}"); return None

    def process_user_dynamic(self, patient_data, report, original_problem="General Checkup"):
        dept, color, level = self.get_triage_info(report)
        today = datetime.now().strftime("%Y-%m-%d")
        major_count, dept_count = 0, 0
        if self.db: major_count, dept_count = self.db.get_counts(today, dept)

        data = {
            "name": patient_data['name'], "age": patient_data['age'], 
            "mobile": patient_data['mobile'], "date": today,
            "major_id": major_count + 1, 
            "sub_token": f"{dept[:4].upper()}-{(dept_count + 1):03d}",
            "main_problem": original_problem
        }
        if self.db: self.db.save_token(today, data['sub_token'], dept, data['name'])
        return data, self.generate_pdf(data, report, dept, color, level)